// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psjwczdyybkzufkkggqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzandjemR5eWJrenVma2tnZ3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMjg1MTgsImV4cCI6MjA2MDcwNDUxOH0.JUSDhRWe91UI3TtXauquGYRVo-1ROqI791ajC9FR94s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);